# Generated by Django 4.2.1 on 2023-06-04 15:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Auteur',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nomAuteur', models.CharField(max_length=25)),
                ('prenomAuteur', models.CharField(max_length=25)),
                ('ageAuteur', models.IntegerField(blank=True, null=True)),
                ('photoAuteur', models.ImageField(upload_to='')),
            ],
        ),
        migrations.CreateModel(
            name='Cat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nomCat', models.CharField(max_length=100)),
                ('descriptifCat', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='Jeu',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titreJeu', models.CharField(max_length=50)),
                ('anneeJeu', models.DateField()),
                ('photoJeu', models.ImageField(upload_to='')),
                ('editeurJeu', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Joueur',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nomJoueur', models.CharField(max_length=25)),
                ('prenomJoueur', models.CharField(max_length=25)),
                ('emailJoueur', models.EmailField(max_length=254)),
                ('mdpJoueur', models.CharField(max_length=30)),
            ],
        ),
    ]
