# Generated by Django 4.2.1 on 2023-06-12 19:38

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Auteur',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nomAuteur', models.CharField(max_length=25)),
                ('prenomAuteur', models.CharField(max_length=25)),
                ('ageAuteur', models.IntegerField(blank=True, null=True)),
                ('photoAuteur', models.ImageField(blank=True, default=None, null=True, upload_to='images/')),
            ],
        ),
        migrations.CreateModel(
            name='Cat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nomCat', models.CharField(max_length=100)),
                ('descriptifCat', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='Jeu',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titreJeu', models.CharField(max_length=50)),
                ('anneeJeu', models.IntegerField()),
                ('photoJeu', models.ImageField(blank=True, null=True, upload_to='images/')),
                ('editeurJeu', models.CharField(max_length=50)),
                ('auteurJeu', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='ludotheque.auteur')),
                ('categorieJeu', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='ludotheque.cat')),
            ],
        ),
        migrations.CreateModel(
            name='Joueur',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nomJoueur', models.CharField(max_length=25)),
                ('prenomJoueur', models.CharField(max_length=25)),
                ('emailJoueur', models.EmailField(default='test@test.test', max_length=254)),
                ('mdpJoueur', models.CharField(max_length=30)),
                ('typeJoueur', models.CharField(choices=[('Particulier', 'Particulier'), ('Professionnel', 'Professionnel')], default='Particulier', max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Liste',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('jeuListe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ludotheque.jeu')),
                ('joueurListe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ludotheque.joueur')),
            ],
        ),
        migrations.CreateModel(
            name='Comm',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('noteComm', models.FloatField(max_length=2)),
                ('contenuComm', models.TextField()),
                ('dateComm', models.DateField(default=datetime.datetime(2023, 6, 12, 19, 38, 12, 539619, tzinfo=datetime.timezone.utc))),
                ('jeuComm', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ludotheque.jeu')),
                ('joueurComm', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ludotheque.joueur')),
            ],
        ),
    ]
