# Generated by Django 4.2.1 on 2023-06-05 08:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ludotheque', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Troll',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.IntegerField()),
            ],
        ),
        migrations.AlterField(
            model_name='jeu',
            name='anneeJeu',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='jeu',
            name='photoJeu',
            field=models.ImageField(blank=True, upload_to=''),
        ),
    ]
