# Generated by Django 4.2.1 on 2023-06-12 19:46

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ludotheque', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auteur',
            name='photoAuteur',
            field=models.ImageField(blank=True, default='/media/default.png', null=True, upload_to='images/'),
        ),
        migrations.AlterField(
            model_name='comm',
            name='dateComm',
            field=models.DateField(default=datetime.datetime(2023, 6, 12, 19, 46, 20, 747828, tzinfo=datetime.timezone.utc)),
        ),
    ]
