# Generated by Django 4.2.2 on 2023-06-12 14:17

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ludotheque', '0002_troll_alter_jeu_anneejeu_alter_jeu_photojeu'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comm',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('noteComm', models.FloatField(max_length=2)),
                ('contenuComm', models.TextField()),
                ('dateComm', models.DateField(default=datetime.datetime(2023, 6, 12, 14, 17, 30, 744549, tzinfo=datetime.timezone.utc))),
            ],
        ),
        migrations.CreateModel(
            name='Liste',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.DeleteModel(
            name='Troll',
        ),
        migrations.AddField(
            model_name='jeu',
            name='auteurJeu',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='ludotheque.auteur'),
        ),
        migrations.AddField(
            model_name='jeu',
            name='categorieJeu',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='ludotheque.cat'),
        ),
        migrations.AddField(
            model_name='joueur',
            name='typeJoueur',
            field=models.CharField(choices=[('Particulier', 'Particulier'), ('Professionnel', 'Professionnel')], default='Particulier', max_length=30),
        ),
        migrations.AlterField(
            model_name='auteur',
            name='photoAuteur',
            field=models.ImageField(blank=True, null=True, upload_to='images/'),
        ),
        migrations.AlterField(
            model_name='jeu',
            name='photoJeu',
            field=models.ImageField(blank=True, upload_to='images'),
        ),
        migrations.AlterField(
            model_name='joueur',
            name='emailJoueur',
            field=models.EmailField(default='test@test.test', max_length=254),
        ),
        migrations.AddField(
            model_name='liste',
            name='jeuListe',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ludotheque.jeu'),
        ),
        migrations.AddField(
            model_name='liste',
            name='joueurListe',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ludotheque.joueur'),
        ),
        migrations.AddField(
            model_name='comm',
            name='jeuComm',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ludotheque.jeu'),
        ),
        migrations.AddField(
            model_name='comm',
            name='joueurComm',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ludotheque.joueur'),
        ),
    ]
