# Generated by Django 4.1.5 on 2023-06-08 08:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ludotheque', '0002_troll_alter_jeu_anneejeu_alter_jeu_photojeu'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auteur',
            name='photoAuteur',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
