# Generated by Django 4.1.5 on 2023-06-08 09:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ludotheque', '0003_alter_auteur_photoauteur'),
    ]

    operations = [
        migrations.AddField(
            model_name='joueur',
            name='typeJoueur',
            field=models.CharField(choices=[('Particulier', 'Particulier'), ('Professionnel', 'Professionnel')], default='Particulier', max_length=30),
        ),
    ]
