# Generated by Django 4.1.5 on 2023-06-08 18:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ludotheque', '0004_joueur_typejoueur'),
    ]

    operations = [
        migrations.AddField(
            model_name='jeu',
            name='auteurJeu',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='ludotheque.auteur'),
        ),
        migrations.AddField(
            model_name='jeu',
            name='categorieJeu',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='ludotheque.cat'),
        ),
        migrations.AlterField(
            model_name='joueur',
            name='emailJoueur',
            field=models.EmailField(default='test@test.test', max_length=254),
        ),
    ]
