# Generated by Django 4.1.5 on 2023-06-11 10:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ludotheque', '0005_jeu_auteurjeu_jeu_categoriejeu_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Liste',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('jeuListe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ludotheque.jeu')),
                ('joueurListe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ludotheque.joueur')),
            ],
        ),
        migrations.CreateModel(
            name='Comm',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('noteComm', models.FloatField()),
                ('contenuComm', models.TextField()),
                ('jeuComm', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ludotheque.jeu')),
                ('joueurComm', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ludotheque.joueur')),
            ],
        ),
    ]
