# Generated by Django 4.1.5 on 2023-06-11 12:05

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ludotheque', '0006_liste_comm'),
    ]

    operations = [
        migrations.AddField(
            model_name='comm',
            name='dateComm',
            field=models.DateField(default=datetime.datetime(2023, 6, 11, 12, 5, 18, 406511, tzinfo=datetime.timezone.utc)),
        ),
    ]
