# Generated by Django 4.1.5 on 2023-06-11 14:42

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ludotheque', '0007_comm_datecomm'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comm',
            name='dateComm',
            field=models.DateField(default=datetime.datetime(2023, 6, 11, 14, 42, 7, 517859, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='comm',
            name='noteComm',
            field=models.FloatField(max_length=2),
        ),
    ]
