# Generated by Django 4.2.1 on 2023-06-12 13:12

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ludotheque', '0008_alter_comm_datecomm_alter_comm_notecomm'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Troll',
        ),
        migrations.AlterField(
            model_name='comm',
            name='dateComm',
            field=models.DateField(default=datetime.datetime(2023, 6, 12, 13, 12, 22, 350809, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='jeu',
            name='photoJeu',
            field=models.ImageField(blank=True, upload_to='images'),
        ),
    ]
