# Generated by Django 4.2.1 on 2023-06-12 13:24

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ludotheque', '0009_delete_troll_alter_comm_datecomm_alter_jeu_photojeu'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auteur',
            name='photoAuteur',
            field=models.FileField(blank=True, null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='comm',
            name='dateComm',
            field=models.DateField(default=datetime.datetime(2023, 6, 12, 13, 24, 19, 846303, tzinfo=datetime.timezone.utc)),
        ),
    ]
