# Generated by Django 4.2.1 on 2023-06-12 13:38

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ludotheque', '0010_alter_auteur_photoauteur_alter_comm_datecomm'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auteur',
            name='photoAuteur',
            field=models.ImageField(null=True, upload_to='images/'),
        ),
        migrations.AlterField(
            model_name='comm',
            name='dateComm',
            field=models.DateField(default=datetime.datetime(2023, 6, 12, 13, 38, 52, 478518, tzinfo=datetime.timezone.utc)),
        ),
    ]
