# Generated by Django 4.2.1 on 2023-06-12 19:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ludotheque', '0003_comm_liste_delete_troll_jeu_auteurjeu_and_more'),
        ('ludotheque', '0012_alter_comm_datecomm'),
    ]

    operations = [
    ]
